---
- name: Deploy n8n instances using Docker Compose
  hosts: all
  become: true
  vars:
    n8n_instances:
      - subdomain: n8n1
        domain_name: n8n1.sqwacker.com
        n8n_port: 5678
        timezone: Australia/Adelaide
      - subdomain: n8n2
        domain_name: n8n2.sqwacker.com
        n8n_port: 5679
        timezone: UTC

  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
      tags: docker

    - name: Ensure docker-compose is installed
      apt:
        name: docker-compose
        state: present
      tags: docker

    - name: Create project folders
      file:
        path: "/opt/{{ item.subdomain }}"
        state: directory
      loop: "{{ n8n_instances }}"

    - name: Copy docker-compose template
      template:
        src: docker-compose.yml.j2
        dest: "/opt/{{ item.subdomain }}/docker-compose.yml"
      loop: "{{ n8n_instances }}"

    - name: Stop and remove existing containers
      docker_compose:
        project_src: "/opt/{{ item.subdomain }}"
        state: absent
      loop: "{{ n8n_instances }}"
      ignore_errors: true

    - name: Deploy docker-compose stack
      docker_compose:
        project_src: "/opt/{{ item.subdomain }}"
        state: present
      loop: "{{ n8n_instances }}"
