---
- name: Install and Configure n8n Instances
  hosts: all
  become: yes
  vars:
    n8n_instances:
      - subdomain: n8n1.sqwacker.net
        domain_name: n8n1.sqwacker.net
        n8n_port: 5678
        timezone: "Australia/Adelaide"
      - subdomain: n8n2.sqwacker.net
        domain_name: n8n2.sqwacker.net
        n8n_port: 5679
        timezone: "UTC"

  tasks:
    - name: Copy docker-compose template
      template:
        src: docker-compose.yml.j2
        dest: "/home/{{ ansible_user }}/docker-compose-{{ item.subdomain }}.yml"
      with_items: "{{ n8n_instances }}"

    - name: Create directory for n8n container data
      file:
        path: "/home/{{ ansible_user }}/n8n-data/{{ item.subdomain }}"
        state: directory
      with_items: "{{ n8n_instances }}"

    - name: Pull docker images for n8n
      docker_image:
        name: "{{ item.subdomain }}"
        source: pull
      with_items: "{{ n8n_instances }}"

    - name: Start n8n containers
      docker_compose:
        project_src: "/home/{{ ansible_user }}/"
        files:
          - "/home/{{ ansible_user }}/docker-compose-{{ item.subdomain }}.yml"
        state: present
      with_items: "{{ n8n_instances }}"
