---
- name: Deploy n8n containers
  hosts: n8n
  become: yes
  vars:
    timezone: "UTC"
  tasks:

    - name: Install prerequisite packages
      apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Create keyrings directory
      file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add Docker's official GPG key (dearmored)
      shell: |
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
      args:
        creates: /etc/apt/keyrings/docker.gpg

    - name: Set permissions on Docker GPG key
      file:
        path: /etc/apt/keyrings/docker.gpg
        mode: '0644'

    - name: Add Docker APT repository
      apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        filename: docker
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker Engine and Docker Compose plugin
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Add current user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Enable and start Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Create project directory
      file:
        path: /opt/n8n_{{ inventory_hostname }}
        state: directory
        mode: '0755'

    - name: Copy docker-compose.yml template
      template:
        src: docker-compose.yml.j2
        dest: /opt/n8n_{{ inventory_hostname }}/docker-compose.yml
        mode: '0644'

    - name: Launch n8n containers
      shell: /usr/bin/docker compose up -d
      args:
        chdir: /opt/n8n_{{ inventory_hostname }}
